[colors.bright]
black = "0x282828"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfe8019"

[colors.cursor]
cursor = "0xebdbb2"
text = "0xebdbb2"

[colors.normal]
black = "0x282828"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[font]
size = 14.5

[window]
opacity = 0.95

[window.padding]
x = 5
y = 5
